### ISSUE TITLE
Installation error: vpm has not yet been packaged for your architecture (x86_64-unknown-linux-musl)

### ISSUE THREAD

**Issue by Harris-Alphacore** [getinstachip/vpm#26]
As the Title states
![image](https://github.com/user-attachments/assets/57ea6731-7f37-4058-b31f-0695a812cc3d)

**Comment by sathvikr** [comment]
Weird, will take a look. Thanks for posting.

**Comment by sathvikr** [comment]
Should be fixed now!

**Comment by Harris-Alphacore** [comment]
Issue fixed Thank you!
